[versions]
android-plugin = "8.2.2"
java = "1.8"
kotlin = "1.9.22"
kotlin-coroutines = "1.7.3"
kotlin-ksp = "1.9.22-1.0.17"
androidx-core = "1.12.0"
androidx-versionedparcelable = "1.2.0"
androidx-arch-core = "2.2.0"
androidx-annotation = "1.7.1"
androidx-collection = "1.4.0"
androidx-concurrent = "1.1.0"
androidx-lifecycle = "2.7.0"
androidx-activity = "1.8.2"
androidx-compose-compiler = "1.5.8"
androidx-compose-runtime = "1.6.0"
androidx-compose-ui = "1.6.0"
androidx-compose-foundation = "1.6.0"
androidx-compose-animation = "1.6.0"
androidx-compose-material = "1.6.0"
androidx-compose-material3 = "1.2.0-rc01"
androidx-navigation = "2.7.6"
androidx-startup = "1.1.1"
androidx-window = "1.2.0"
androidx-work = "2.9.0"
androidx-media3 = "1.2.1"
androidx-hilt = "1.1.0"
androidx-test-junit = "1.1.5"
androidx-test-espresso = "3.5.1"
androix-test-uiautomator = "2.2.0"
androidx-baselineprofile = "1.2.2"
androidx-profileinstaller = "1.3.1"
hilt = "2.50"
okhttp = "4.12.0"
okio = "3.7.0"
coil = "2.5.0"
junit = "4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
android-test = { id = "com.android.test", version.ref = "android-plugin" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-baselineprofile" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-arch-core-common = { group = "androidx.arch.core", name = "core-common", version.ref = "androidx-arch-core" }
androidx-arch-core-runtime = { group = "androidx.arch.core", name = "core-runtime", version.ref = "androidx-arch-core" }
androidx-versionedparcelable = { group = "androidx.versionedparcelable", name = "versionedparcelable", version.ref = "androidx-versionedparcelable" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "androidx-annotation" }
androidx-collection = { group = "androidx.collection", name = "collection", version.ref = "androidx-collection" }
androidx-collection-ktx = { group = "androidx.collection", name = "collection-ktx", version.ref = "androidx-collection" }
androidx-concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures", version.ref = "androidx-concurrent" }
androidx-concurrent-futures-ktx = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "androidx-concurrent" }
androidx-lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-livadata = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-core = { group = "androidx.lifecycle", name = "lifecycle-livedata-core", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-core-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "androidx-compose-runtime" }
androidx-compose-runtime-saveable = { group = "androidx.compose.runtime", name = "runtime-saveable", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-geometry = { group = "androidx.compose.ui", name = "ui-geometry", version.ref = "androidx-compose-ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "androidx-compose-ui" }
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit", version.ref = "androidx-compose-ui" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-data = { group = "androidx.compose.ui", name = "ui-tooling-data", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-compose-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose-ui" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose-ui" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "androidx-compose-foundation" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "androidx-compose-animation" }
androidx-compose-animation-core = { group = "androidx.compose.animation", name = "animation-core", version.ref = "androidx-compose-animation" }
androidx-compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics", version.ref = "androidx-compose-animation" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "androidx-compose-material" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidx-compose-material" }
androidx-compose-material-ripple = { group = "androidx.compose.material", name = "material-ripple", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-compose-material3-wsc = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidx-compose-material3" }
androidx-navigation-common = { group = "androidx.navigation", name = "navigation-common", version.ref = "androidx-navigation" }
androidx-navigation-common-ktx = { group = "androidx.navigation", name = "navigation-common-ktx", version.ref = "androidx-navigation" }
androidx-navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "androidx-navigation" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "androidx-navigation" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-test = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidx-navigation" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidx-window" }
androidx-window-core = { group = "androidx.window", name = "window-core", version.ref = "androidx-window" }
androidx-window-java = { group = "androidx.window", name = "window-java", version.ref = "androidx-window" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "androidx-work" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "androidx-media3" }
androidx-media3-database = { group = "androidx.media3", name = "media3-database", version.ref = "androidx-media3" }
androidx-media3-datasource = { group = "androidx.media3", name = "media3-datasource", version.ref = "androidx-media3" }
androidx-media3-datasource-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "androidx-media3" }
androidx-media3-container = { group = "androidx.media3", name = "media3-container", version.ref = "androidx-media3" }
androidx-media3-extractor = { group = "androidx.media3", name = "media3-extractor", version.ref = "androidx-media3" }
androidx-media3-decoder = { group = "androidx.media3", name = "media3-decoder", version.ref = "androidx-media3" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidx-media3" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "androidx-hilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt" }
androidx-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation", version.ref = "androidx-hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-test-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-test-junit" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androix-test-uiautomator" }
androidx-baselineprofile = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-baselineprofile" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidx-profileinstaller" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
coil-video = { group = "io.coil-kt", name = "coil-video", version.ref = "coil" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[bundles]
kotlin = ["kotlin-stdlib", "kotlin-stdlib-jdk7", "kotlin-stdlib-jdk8", "kotlin-reflect", "kotlin-coroutines-core", "kotlin-coroutines-android"]
androidx-core = ["androidx-core", "androidx-core-ktx"]
androidx-arch-core = ["androidx-arch-core-common", "androidx-arch-core-runtime"]
androidx-annotation = ["androidx-annotation", "androidx-annotation-jvm"]
androidx-collection = ["androidx-collection", "androidx-collection-ktx"]
androidx-concurrent = ["androidx-concurrent-futures", "androidx-concurrent-futures-ktx"]
androidx-lifecycle = ["androidx-lifecycle-common", "androidx-lifecycle-common-java8", "androidx-lifecycle-runtime", "androidx-lifecycle-runtime-compose", "androidx-lifecycle-runtime-ktx", "androidx-lifecycle-livedata", "androidx-lifecycle-livedata-ktx", "androidx-lifecycle-livedata-core", "androidx-lifecycle-livedata-core-ktx", "androidx-lifecycle-viewmodel", "androidx-lifecycle-viewmodel-savedstate", "androidx-lifecycle-viewmodel-compose", "androidx-lifecycle-viewmodel-ktx"]
androidx-activity = ["androidx-activity", "androidx-activity-compose", "androidx-activity-ktx"]
androidx-compose = ["androidx-compose-runtime", "androidx-compose-runtime-livedata", "androidx-compose-runtime-saveable", "androidx-compose-ui", "androidx-compose-ui-geometry", "androidx-compose-ui-graphics", "androidx-compose-ui-unit", "androidx-compose-ui-util", "androidx-compose-foundation", "androidx-compose-foundation-layout", "androidx-compose-animation", "androidx-compose-animation-core", "androidx-compose-animation-graphics", "androidx-compose-material-icons-core", "androidx-compose-material-icons-extended", "androidx-compose-material-ripple", "androidx-compose-material3", "androidx-compose-material3-wsc"]
androidx-compose-tooling = ["androidx-compose-ui-tooling", "androidx-compose-ui-tooling-data", "androidx-compose-ui-tooling-preview"]
androidx-navigation = ["androidx-navigation-common", "androidx-navigation-common-ktx", "androidx-navigation-runtime", "androidx-navigation-runtime-ktx", "androidx-navigation-compose"]
androidx-window = ["androidx-window", "androidx-window-core", "androidx-window-java"]
androidx-work = ["androidx-work-runtime", "androidx-work-runtime-ktx"]
androidx-media3 = ["androidx-media3-common", "androidx-media3-database", "androidx-media3-datasource", "androidx-media3-datasource-okhttp", "androidx-media3-decoder", "androidx-media3-container", "androidx-media3-extractor", "androidx-media3-exoplayer"]
androidx-test = ["androidx-test-junit", "androidx-test-junit-ktx", "androidx-test-espresso"]
hilt = ["hilt", "androidx-hilt-common", "androidx-hilt-work", "androidx-hilt-navigation", "androidx-hilt-navigation-compose"]
hilt-compiler = ["hilt-compiler", "androidx-hilt-compiler"]
coil = ["coil", "coil-compose", "coil-gif", "coil-svg", "coil-video"]
